### ISSUE TITLE
Switch to empty PATCH when migrating resources

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/kube-storage-version-migrator#65]
Looking here:
https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/a8167b3423eea207dddc0174b21b958c400ded5f/pkg/migrator/core.go#L63-L77

I notice that the migrator uses Updates/PUTs to perform the storage migration. Is it necessary to do the full PUT? This [presentation](https://youtu.be/HsYtMvvzDyI?t=1221) makes it seems like an empty patch will suffice.

**Comment by caesarxuchao** [comment]
I can't remember why we chose to do a full GET-UPDATE cycle instead of an empty patch. @roycaihw @lavalamp do you remember?

**Comment by lavalamp** [comment]
Would an empty patch actually trigger the server to do a write?

**Comment by dprotaso** [comment]
I've manually tested it with the tool I wrote for Knative [here](https://github.com/knative/pkg/blob/master/apiextensions/storageversion/migrator.go)

The assumption I have is that you can only remove entries from the CRD's `status.storageVersions` list only if there are no resources being stored at that version. 

After the tool patches all the resources I'm able to drop older storage versions - so I believe PATCH'ing causes a server write. If not then...

**Comment by roycaihw** [comment]
> you can only remove entries from the CRD's status.storageVersions list only if there are no resources being stored at that version.

I don't think the apiserver checks/tracks all the CRs before updating the CRD

**Comment by roycaihw** [comment]
I cannot think of a reason for not doing an empty patch either. The only [short-circuit](https://github.com/kubernetes/kubernetes/blob/686ffd397f679472b62d1345f2e8ad507c80b342/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L333-L336) that I'm aware of happens after encoding (and conversion). I tried empty-patching a stale CR (noop conversion). The write didn't get short-circuited. I assume it's because the [encoding](https://github.com/kubernetes/kubernetes/blob/686ffd397f679472b62d1345f2e8ad507c80b342/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L314) sets the `apiVersion` of the new object to be different from the old data.

**Comment by roycaihw** [comment]
/assign

Let me add some test and do the switch

**Comment by roycaihw** [comment]
Talked with @caesarxuchao. The reason we did UPDATE instead of PATCH was because UPDATE is more general. There can be aggregated apiservers who don't implement patchers (e.g. [jsonPatcher](https://github.com/kubernetes/kubernetes/blob/3f7e26decee627ea37ab217fc1b48698400f01e8/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L298-L302)) and therefore don't support [PATCH](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/78600c35396b3992e058163885a16d677bcb3ee8/pkg/initializer/discover.go#L108). 

We also discussed the existing UPDATE code, and found that we can improve the performance by avoiding retry on conflict https://github.com/kubernetes-sigs/kube-storage-version-migrator/issues/78 (note that we already skipped the initial GET before UPDATE)-- then the throughput for UPDATE v.s. PATCH would be:

- UPDATE: list all items, one update request for each item
- PATCH: list all items, one patch request for each item

So the performance would be similar, while UPDATE is easier for aggregated apiservers to support. 

/close

**Comment by dprotaso** [comment]
Doesn't `UPDATE` require clients to send the entire resource?

**Comment by caesarxuchao** [comment]
> Doesn't UPDATE require clients to send the entire resource?

Yes. However, because the list operation already downloads the entire resource, so the UPDATE just doubles the bandwidth cost, it's not a difference in the order of magnitude.

Converting to PATCH does improve the performance, but it also means that we need to handle more corner cases like https://github.com/kubernetes-sigs/kube-storage-version-migrator/issues/65#issuecomment-703930487 mentioned, so I think it's not our current priority to convert to PATCH.

That said, if using UPDATE is causing performance bottleneck in production, please let us know, we are willing to improve the performance now.
